# Chulapa theme configuration
remote_theme: dieghernan/chulapa

# Required plugins for Chulapa theme
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-include-cache

# Site Settings and SEO
locale: "en-US"
title: Godot Synth Engine
title_separator: " | "
subtitle: A powerful and flexible synthesizer engine for Godot 4
description: A powerful and flexible synthesizer engine for Godot 4 providing virtual analog synthesis with extensive modulation capabilities
url: https://eclipsinglines.github.io
baseurl: /GodotSynth
repository: EclipsingLines/GodotSynth
author:
   name: EclipsingLines
   links:
     - url: https://linktr.ee/eclipsinglines
       icon: "fas fa-link"
       label: Linktree
# Theme and layout settings
chulapa-skin:
  skin  : solar
  highlight   : "ZENBURN"
navbar: true
header_type: base
footer: true
footer_custom: 'Copyright &copy; <a href="https://linktr.ee/eclipsinglines" target="_blank">EclipsingLines</a> 2025'

# Navigation
navbar_fixed: true
navbar_list:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: Engines
    url: /engines
  - title: Modulation
    url: /modulation
  - title: Effects
    url: /effects
  - title: GitHub
    url: https://github.com/EclipsingLines/GodotSynth

# Social links (optional)
social:
  github: EclipsingLines/GodotSynth

# FontAwesome
fa_version: "6"

# Search settings (optional)
search:
  provider: lunr
  label: Search
  landing_page: /search
